resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/wasm-build:1.2

jobs:
- job: VS_Latest
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache
    SourceLinkEnabled: false

  steps:
  - task: GitVersion@3
    inputs:
      updateAssemblyInfo: false   

  - task: MSBuild@1
    inputs:
      solution: 'C#\Uno\Uno.RayTraceBenchmark.sln'
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release "/p:PackageVersion=%GITVERSION_FullSemVer%" "/p:InformationalVersion=%GITVERSION_InformationalVersion%" /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: 'C#\Uno\RayTraceBenchmark\RayTraceBenchmark.Wasm\bin\Release\netstandard2.0\dist'
      artifactType: container
      artifactName: RayTraceBenchmark-Wasm

- job: linux
  container: nv-bionic-wasm

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget
    EMSCRIPTEN_VERSION: 1.38.45-upstream

  steps:
  - checkout: self
    clean: true

  - bash: |
      cd /emsdk
      echo Installing emscripten $(EMSCRIPTEN_VERSION)
      sudo git reset HEAD --hard
      sudo git pull
      sudo ./emsdk update-tags
      sudo ./emsdk install $(EMSCRIPTEN_VERSION)
      sudo ./emsdk activate $(EMSCRIPTEN_VERSION)
      sudo chmod -R 777 /emsdk
      sudo chmod -R 777 ~/.emscripten_cache

    displayName: 'Setup Emscripten'

  - bash: |
      cd /emsdk
      wget https://raw.githubusercontent.com/mono/mono/master/sdks/builds/emscripten-pr-8457.diff
      wget https://raw.githubusercontent.com/mono/mono/master/sdks/builds/fix-emscripten-8511.diff
      cd /emsdk/upstream/emscripten
      patch -N -p1 < /emsdk/emscripten-pr-8457.diff
      patch -N -p1 < /emsdk/fix-emscripten-8511.diff

    displayName: 'Apply Emscripten Mono patches'

  - task: GitVersion@4
    inputs:
      updateAssemblyInfo: false

  - script: |
      source /emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" "$(build.sourcesdirectory)/C#/Uno/RayTraceBenchmark/RayTraceBenchmark.Wasm/RayTraceBenchmark.Wasm.csproj"

    env:
      GITVERSION_INFORMATIONALVERSION: $(GITVERSION_INFORMATIONALVERSION)

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: '$(build.sourcesdirectory)/C#/Uno/RayTraceBenchmark/RayTraceBenchmark.Wasm/bin/Release/netstandard2.0/dist'
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: aot-drop
      ArtifactType: Container